apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: VpcContractGenerator
  labels:
    move2kube.konveyor.io/built-in: false
spec:
  class: "Starlark"
  directoryDetect:
    levels: 0
  config:
    starFile: "vpccontractgenerator.star"
  invokesByDefault:
    enabled: true
