apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: TerraformHerokuTransformer
  labels:
    move2kube.konveyor.io/built-in: false
spec:
  class: "Starlark"
  directoryDetect:
    levels: 0
  config:
    starFile: "terraform_heroku.star"
  invokedByDefault:
    enabled: true
  override:
    matchLabels: 
      move2kube.konveyor.io/built-in: "true"