apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: AddAnnotation
  labels: 
    move2kube.konveyor.io/built-in: false
spec:
  class: "WasmTransformer"
  consumes:
    KubernetesYamls: 
      merge: false
      # Ensures a artifact of this type gets immediately intercepted by this transformer
      mode: "MandatoryPassThrough" 
  produces:
    KubernetesYamls:
      disabled: false
  config:
    wasmFile: "maintiny.wasm"
