apiVersion: move2kube.konveyor.io/v1alpha1
kind: Parameterizer
metadata:
  name: multiple-parameterizers
spec:
  parameterizers:
    - target: "spec.replicas"
      template: "${common.replicas}"
      default: 10
      filters:
        - kind: Deployment
          apiVersion: ".*/v1.*"
    - target: 'spec.template.spec.containers.[containerName:name].image'
      template: '${imageregistry.url}/${imageregistry.namespace}/${services.$(metadataName).containers.$(containerName).image.name}:${services.$(metadataName).containers.$(containerName).image.tag}'
      default: us.icr.io/move2kube/myimage:latest
      filters:
        - kind: Deployment
          apiVersion: ".*/v1.*"
      parameters:
        - name: services.$(metadataName).containers.$(containerName).image.name
          values:
          - envs: [dev, staging, prod]
            metadataName: nginx
            value: nginx-allenvs
          - envs: [prod]
            metadataName: javaspringapp
            value: openjdk-prod8
            custom:
              containerName: apicontainer
          - envs: [dev]
            metadataName: javaspringapp
            value: openjdk-dev8
            custom:
              containerName: apicontainer
          - envs: [prod]
            metadataName: javaspringapp
            value: mysql-prod
            custom:
              containerName: mysqlcontainer
          - envs: [dev]
            metadataName: javaspringapp
            value: mysql-dev
            custom:
              containerName: mysqlcontainer
