apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: IngressAnnotator
  labels: 
    move2kube.konveyor.io/built-in: false
spec:
  class: "Starlark"
  consumes:
    KubernetesYamls: 
      merge: false
      # Ensures a artifact of this type gets immediately intercepted by this transformer
      mode: "MandatoryPassThrough" 
  produces:
    KubernetesYamls:
      disabled: false
  config:
    starFile: "ingress-annotator.star"
