apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: NativeTransformer
  labels: 
    move2kube.konveyor.io/inbuilt: false
spec:
  class: "Executable"
  isolated: true
  override:
    matchLabels: 
      move2kube.konveyor.io/built-in: "true"
  directoryDetect:
    levels: 1
  consumes:
    Service:
      merge: false
  config:
    platforms: 
      - "darwin"
    directoryDetectCMD: ["/usr/local/bin/python3", "./detect.py"]
    transformCMD: ["/usr/local/bin/python3", "./transform.py"]
    detectScriptIO:
      input:
        mode: env
        envName: "DETECT_INPUT_PATH"
      output:
        mode: arg
    transformScriptIO:
      input:
        mode: arg
      output:
        mode: env
        envName: "TRANSFORM_OUTPUT_PATH"

