apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: ContainerizedTransformer
  labels: 
    move2kube.konveyor.io/inbuilt: false
spec:
  mode: "Container"
  class: "Executable"
  isolated: true
  override:
    matchLabels: 
      move2kube.konveyor.io/built-in: "true"
  directoryDetect:
    levels: 1
  consumes:
    Service:
      merge: false
  config:
    platforms: 
      - "darwin"
    directoryDetect:
      cmd: ["python", "./detect.py"]
      input:
        mode: env
        envName: "DETECT_INPUT_PATH"
      output:
        mode: arg
    transform: 
      cmd: ["python", "./transform.py"]
      input:
        mode: arg
      output:
        mode: env
        envName: "TRANSFORM_OUTPUT_PATH"
    container: 
      image: containerizedtransformer:latest
      workingDir: "/m2k/"
      keepAliveCommand: ["tail", "-f", "/dev/null"]
      build:
        dockerfile: "Dockerfile"
        context: "."
