apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: ContainerizedTransformer
  labels: 
    move2kube.konveyor.io/inbuilt: false
spec:
  mode: "Container"
  class: "Executable"
  isolated: true
  override:
    matchLabels: 
      move2kube.konveyor.io/built-in: "true"
  directoryDetect:
    levels: 1
  consumes:
    Service:
      merge: false
  config:
    platforms: 
      - "darwin"
    directoryDetectCMD: ["python", "./detect.py", "$M2K_DETECT_INPUT_PATH", "$M2K_DETECT_OUTPUT_PATH"]
    transformCMD: ["python", "./transform.py"]
    container: 
      image: containerizedtransformer:latest
      workingDir: "/m2k/"
      keepAliveCommand: ["tail", "-f", "/dev/null"]
      build:
        dockerfile: "Dockerfile"
        context: "."
