apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: IngressAnnotator
spec:
  mode: "Container"
  class: "Starlark"
  consumes:
    - "KubernetesYamls"
  config:
    starFile: "ingress-annotator.star"
