apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: InvokeDetect
  labels:
    move2kube.konveyor.io/built-in: false
spec:
  class: "InvokeDetect"
  directoryDetect:
    levels: 0
  consumes:
    InvokeDetect:
      merge: false
  produces:
    "*":
      disabled: false
