apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: Nodejs-CustomFiles
  labels:
    move2kube.konveyor.io/task: containerization
    move2kube.konveyor.io/built-in: false
spec:
  class: "NodejsDockerfileGenerator"
  directoryDetect:
    levels: -1
  consumes:
    Service: 
      merge: false
  produces:
    Dockerfile:
      disabled: false
    DockerfileForService:
      disabled: false
  override:
    matchLabels: 
      move2kube.konveyor.io/name: Nodejs-Dockerfile
